// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAFBLKDZpRWrzlOfFFwpl0VIMh9s6JD9o',
    appId: '1:668764689770:web:4694da026415c73a758113',
    messagingSenderId: '668764689770',
    projectId: 'my-library-a2671',
    authDomain: 'my-library-a2671.firebaseapp.com',
    storageBucket: 'my-library-a2671.firebasestorage.app',
    measurementId: 'G-NR40MJ1E9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPFOukzUE2BN-bxZmm22A2W7sjrhdAyyQ',
    appId: '1:668764689770:android:de20fb68e0619eb4758113',
    messagingSenderId: '668764689770',
    projectId: 'my-library-a2671',
    storageBucket: 'my-library-a2671.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD50Gotsjo89DUW3KmzuLli_Q6dSx-J9nA',
    appId: '1:668764689770:ios:952300960132fc34758113',
    messagingSenderId: '668764689770',
    projectId: 'my-library-a2671',
    storageBucket: 'my-library-a2671.firebasestorage.app',
    androidClientId: '668764689770-0gejhj11bnn0aqeeu6nqk4l58c7afvn5.apps.googleusercontent.com',
    iosClientId: '668764689770-pgf1m71vr134475pfi2f9c9g11i4p453.apps.googleusercontent.com',
    iosBundleId: 'com.project.libraryOffline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAFBLKDZpRWrzlOfFFwpl0VIMh9s6JD9o',
    appId: '1:668764689770:web:dac99d971e0fea0f758113',
    messagingSenderId: '668764689770',
    projectId: 'my-library-a2671',
    authDomain: 'my-library-a2671.firebaseapp.com',
    storageBucket: 'my-library-a2671.firebasestorage.app',
    measurementId: 'G-WRRF7CL51W',
  );
}
